### ISSUE TITLE
UBL in YAML

### ISSUE THREAD

**Issue by szepeviktor** [ericmann/invoices#1]
@ericmann Have you considered an existing standard?
https://docs.oasis-open.org/ubl/UBL-2.4.html

It could be converted to YAML
```yaml
Invoice:
  UBLVersionID: "2.1"
  ID: "INV-001"
  IssueDate: "2025-05-31"
  AccountingSupplierParty:
    Party:
      PartyName:
        Name: "Bitmoney LLC"
  AccountingCustomerParty:
    Party:
      PartyName:
        Name: "Customer Kft."
  LegalMonetaryTotal:
    PayableAmount:
      currencyID: "USD"
      value: 1000.00
```
